version: '3'
# To start in production mode, use the commands:
  # docker compose up -d --build
  # docker compose exec backend alembic upgrade head

services:
  database:
    image: postgres:14.3
    container_name: database_recipes
    command: -p 1221
    expose:
      - 1221
    env_file:
      - ./backend/.env-prod

  cache:
    image: redis:latest
    container_name: cache_recipes
    ports:
      - "5370:6379"
    volumes:
      - ./cache:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env-prod
    container_name: backend_recipes
    ports:
      - "8765:8000"
    depends_on:
      - database
      - cache

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_recipes
    environment:
      - VUE_APP_MODE=prod
    ports:
      - "8087:80"
    depends_on:
      - backend