version: '3'
# To start in development mode, use the command: docker-compose -f docker-compose-dev.yml up -d

services:
  database:
    image: postgres:14.3
    container_name: database_recipes
    restart: always
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "1221:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data/pgdata
    command: >
      postgres
        -c logging_collector=on
        -c log_destination=stderr
        -c max_connections=200
        -c shared_buffers=1GB
        -c effective_cache_size=4GB
        -c work_mem=16MB
        -c maintenance_work_mem=512MB
        -c random_page_cost=1.1
        -c temp_file_limit=10GB
        -c log_min_duration_statement=200ms
        -c idle_in_transaction_session_timeout=10s
        -c lock_timeout=1s
        -c statement_timeout=60s
        -c shared_preload_libraries=pg_stat_statements
        -c pg_stat_statements.max=10000
        -c pg_stat_statements.track=all

  cache:
    image: redis:latest
    container_name: cache_recipes
    command: --port 5370
    expose:
      - 5370