version: '3'
# To start in development mode, use the command: docker-compose -f docker-compose-dev.yml up -d

services:
  database:
    image: postgres:14.3
    container_name: database_recipes
    restart: always
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "1221:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data/pgdata

  cache:
    image: redis:latest
    container_name: cache_recipes
    command: --port 5370
    expose:
      - 5370